config/routes.rb
Rails.application.routes.draw do
  root "home#home"

  namespace :api do
    namespace :v1 do
      devise_for :users, :skip => [:sessions], controllers: {registrations: 'api/v1/users/registrations'} do
        devise_scope :user do
            get '/users/sign_out', to: 'devise/sessions#destroy'
        end
      end

      post '/users/sign-in', to: 'authentication#create'

      resources :videogames
      resources :users, except: [:new, :create] do 
        get 'add_game', to: 'users#add_new_game'
        post 'save_game', to: 'users#save_new_game_to_user' 
        post 'remove_game', to: 'users#remove_game_from_user_library'
        post 'create_and_save_game', to: 'users#create_and_save_game_to_user_library'
        post 'connect_steam_account', to: 'users#link_steam_account_to_user'
        post 'import_steam_library', to: 'users#import_steam_library'
      end
    end
  end
  get '*path', to: 'home#home', via: :all
end

app/models/user.rb
require 'dotenv/load'
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :users_videogames
  has_many :videogames, through: :users_videogames

  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :steam_url,  uniqueness: { case_sensitive: false }, allow_blank: true
  validate :correct_steam_url

  def import_steam_library
    if steam_url.nil?
      steam_url_error_message
      return false
    else
      Steam.apikey = ENV["STEAM_API_KEY"]
      imported_games =  Steam::Player.owned_games(steam_id, params: {include_appinfo: 1})
      imported_games["games"].each do |game|
        videogame = Videogame.find_by(game_name: game["name"])
        if videogame.nil?
          new_game = Videogame.new(game_name: game["name"])
          if new_game.save
            self.videogames << new_game
          end
        elsif self.videogames.find_by(game_name: game["name"]).nil?
          self.videogames << videogame
        end
      end
    end

  end
  

  private 

  def correct_steam_url
    if !(self.steam_url.nil?) && self.steam_id.nil? && self.steam_vanity.nil?
      if vanity_url?
        begin
        extrapolate_steam_vanity
        convert_steam_vanity_to_steamID
        rescue Steam::SteamError 
        end
        steam_url_error_message unless valid_steamID?
      elsif id_url?
        extrapolate_steamID
        steam_url_error_message unless valid_steamID?
      else
        steam_url_error_message
      end
    end
  end

  def parsed_steam_url
    parsed_steam_url = self.steam_url.split('/')
  end

  def vanity_url?
    parsed_steam_url[3] == 'id'
  end

  def id_url?
    parsed_steam_url[3] == 'profiles'
  end

  def extrapolate_steamID
    self.steam_id = parsed_steam_url[4]
  end

  def extrapolate_steam_vanity
    Steam.apikey = ENV["STEAM_API_KEY"]
    self.steam_vanity = parsed_steam_url[4]
  end

  def convert_steam_vanity_to_steamID
    Steam.apikey = ENV["STEAM_API_KEY"]
    self.steam_id = Steam::User.vanity_to_steamid(self.steam_vanity)
  end

  def valid_steamID?
    Steam.apikey = ENV["STEAM_API_KEY"]
    !Steam::User.summary(self.steam_id).nil?
  end

  def steam_url_error_message
    errors.add(:steam_url, 'Invalid steam profile URL')
  end

end

app/controllers/api/v1/users/registrations_controller.rb
module Api
  module V1
    class Users::RegistrationsController < Devise::RegistrationsController
      

      def new
        user = User.new
      end
      

      def create
        user = User.new(user_params)
        if user.save
          render json: UserSerializer.new(user).serializable_hash.to_json
        else
          render json: { error: user.errors.messages }, status: 422
        end
      end
      
      def edit
        @user = User.find(params[:id])
      end

      private

      def user_params
        params.require(:user).permit(:username, :email, :steam_id, :password)
      end

      def save_new_game_to_user_params
        params.permit(:game_id, :user_id)
      end

      def create_and_save_game_to_user_library_params
        params.permit(:user_id, :game_name, :developer, :number_of_players)
      end
    end
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < ApplicationController
      include ActionController::HttpAuthentication::Token
      before_action :authenticate_user
      before_action :correct_user_to_edit_profile, only: [:edit, :update, :destroy, :link_steam_account_to_user, :import_steam_library, :create_and_save_game_to_user_library, :remove_game_from_user_library]

      def index
        users = User.all
        render json: UserSerializer.new(users).serializable_hash.to_json
      end

      def show
        user = User.find(params[:id])
        render json: UserSerializer.new(user, options)
      end

      def edit
        @user = current_user
      end

      def update
        user = User.find(params[:id])
        if user.update(user_params)
          render json: UserSerializer.new(user, options).serializable_hash.to_json, status: 200
        else
          render json: { error: user.errors.messages }, status: 422
        end
      end

      def destroy
        user = User.find(params[:id])
        if user.destroy
          head :no_content
        else
          render json: { error: user.errors.messages }, status: 422
        end
      end

      def add_new_game
        @user = current_user
        @videogames = Videogame.all
        @videogame = Videogame.new
      end

      def save_new_game_to_user
        user = User.find(save_new_game_to_user_params[:user_id])
        game = Videogame.find(save_new_game_to_user_params[:game_id])
        user.videogames << game
        render json: UserSerializer.new(user, options).serializable_hash.to_json
      end

      def remove_game_from_user_library
        user = current_user
        game = Videogame.find_by(save_new_game_to_user_params[:game_name])
        user.videogames.delete(game)
        head :no_content
      end

      def create_and_save_game_to_user_library
        params = create_and_save_game_to_user_library_params
        videogame = Videogame.new(game_name: params[:game_name])
        user = current_user
        
        if videogame.save
          user.videogames << videogame
          redirect_to user_path(user)
        else
         render json: { error: videogame.errors.messages }, status: 422
        end
      end

      def link_steam_account_to_user
        params = link_steam_account_to_user_params
        user = current_user
        return render json: {error: 'A Steam Account Is Already Linked To This Profile.'}, status: 422 if !user.steam_url.nil?

        user.steam_url = params[:steamUrl]

        if user.save
          render json: UserSerializer.new(user, options), status: 200
        else
          render json: { error: user.errors.messages }, status: 422
        end

      end

      def import_steam_library
        user = current_user

        if !user.import_steam_library
          user.errors.add(:steam_url, 'Invalid steam profile URL')
          render json: { error: user.errors.messages }, status: 422
        end
      end
      
      private

      def current_user
        token, _options = token_and_options(request)
        @current_user ||= User.find(AuthenticationTokenService.decode_token(token).to_i)

      end

      def authenticate_user
        token, _options = token_and_options(request)
        return render json: {error: 'Unauthorized Access'}, status: 401 if token.nil? || token == 'null'

        begin
          user_id = AuthenticationTokenService.decode_token(token).to_i
          User.find(user_id)
        rescue ActiveRecord::RecordNotFound
          render json: {}, status: 401
        end
      end

      def correct_user_to_edit_profile
        
        token, _options = token_and_options(request)
        render json: {error: 'Unauthorized Access'}, status: 401  if AuthenticationTokenService.decode_token(token) != params[:user_id]
      end

      def user_params
        params.require(:user).permit(:username, :email, :steam_id, :password)
      end

      def save_new_game_to_user_params
        params.permit(:game_name, :user_id)
      end

      def create_and_save_game_to_user_library_params
        params.permit(:user_id, :game_name, :developer, :number_of_players)
      end

      def link_steam_account_to_user_params
        params.require(:user).permit(:steamUrl)
      end

      def is_current_user?(user)
        current_user == user
      end

      def options
        @options ||= { include: %i[videogames] }
      end
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-9 col-md-7 col-lg-4 mx-auto">
        <div class="card card-signin my-5 border border-dark bg-light">
          <div class="card-body">
            <h5 class="card-title text-center">Edit User</h5>
                  <div class="form-label-group">
                    <%= form_with(model: user, :html => {:class => "form"}) do |form| %>
                        <div class="form-control-group">
                        
                          <%= form.label :username %>
                          <%= form.text_field :username, class: "form-control" %>
                          <% user.errors.full_messages_for(:username).each do |message| %>
                            <div><%= message %></div>
                          <% end %>
                        </div>
                        <div class= "form-control-group">
                          <%= form.label :email %>
                          <%= form.email_field :email, class: "form-control" %>
                          <% user.errors.full_messages_for(:email).each do |message| %>
                            <div><%= message %></div>
                          <% end %>
                        </div>
                        <div class= "form-control-group">
                        <%= form.label :steam_id %>
                        <%= form.text_field :steam_id, class: "form-control" %>
                        <% user.errors.full_messages_for(:steam_id).each do |message| %>
                          <div><%= message %></div>
                        <% end %>
                        </div>
                      
                        <div class="action">
                          <%= form.submit "Update User", class: "btn btn-lg btn-primary btn-block text-uppercase" %>
                        </div>
                  <% end %>
                  </form>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/add_new_game.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-9 col-md-7 col-lg-4 mx-auto">
        <div class="card card-signin my-5 border border-dark bg-light">
          <div class="card-body">
            <h3 class="card-title text-center">Add game to library</h3>
                  <div class="form-label-group">

                <h5 class="card-subtitle pb-2"> Link Steam Account </h5>
                    <%= form_with(url: user_connect_steam_account_path, :html => {:class => "form"}) do |form| %>
                      <div class="form-control-group">
                      <%= form.label :steam_URL, class: "text-capitalize" %>
                      <%= form.text_field :steam_url, value: @user.steam_url, class: "form-control" %>
                      </div>

                      <div class="actions">
                      <%= form.submit "Link Steam Account", class: "btn btn-lg btn-primary btn-block text-uppercase" %>
                      </div>
                      <% end %>

                <h5 class="card-subtitle pb-2 pt-2"> Add existing game </h5>

                  <%= form_with(url: user_save_game_path, :html => {:class => "form"}) do |form| %>
                    <div class="form-control-group pb-2">
                      <%= form.select :game_id, @videogames.map { |game| [game.game_name, game.id] }, class: "dropdown" %>
                    </div>

                    <div class="actions">
                    <%= form.submit "Add Existing Game", class: "btn btn-lg btn-primary btn-block text-uppercase" %>
                    </div>
                  <% end %>


                <h5 class="card-subtitle pt-3"> Add new game </h5>
                  <%= form_with(url: user_create_and_save_game_path, :html => {:class => "form"}) do |form| %>
                      <% if @videogame.errors.any? %>
                        <div id="error_explanation">
                          <h2><%= pluralize(@videogame.errors.count, "error") %> prohibited this videogame from being saved:</h2>
                          <ul>
                            <% @videogame.errors.each do |error| %>
                              <li><%= error.full_message %></li>
                            <% end %>
                          </ul>
                        </div>
                      <% end %>
                      
                      <div class="form-control-group">
                          <%= form.label :game_name %>
                          <%= form.text_field :game_name, value: @videogame.game_name, class: "form-control" %>
                      </div>
                      
                      <div class="form-control-group">
                          <%= form.label :developer %>
                          <%= form.text_field :developer, value: @videogame.developer, class: "form-control"  %>
                      </div>
                      
                      <div class="form-control-group">
                          <%= form.label :number_of_players %>
                          <%= form.number_field :number_of_players, value: @videogame.number_of_players, class: "form-control" %>
                      </div>
                      
                      <div class="pt-1 actions">
                      <%= form.submit "Add New Game", class: "btn btn-lg btn-primary btn-block text-uppercase" %>
                      </div>
                  <% end %>

app/views/users/edit.html.erb
<%= render "form", user: @user %>

app/views/users/index.html.erb
<h1> List of Users <h1>

<ul>
  <% @users.each do |user| %>
    <li>
      <%= link_to user.username, user %>
    </li>
  <% end %>
</ul>

<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary" %>

app/views/users/new.html.erb
<h1>Create New User</h1>

<%= render "form", user: @user %>

app/views/users/show.html.erb
  
<div class="container pb-5">  
  <div class="row justify-content-center">
    <div class= "col col-auto text-center border border-dark rounded bg-light">
    <h1>Welcome to <%= @user.username %>'s profile </h1>
    </div>
  </div>

  <div class="row justify-content-center">
    <% if @looking_at_self %>
        <div class="col-auto"
        <button type="button"> <%= link_to "Edit User", edit_user_path(@user),class: "btn btn-sm btn-secondary"%>  </button>
        </div>
        <div class="col-auto">
          <button type="button"
            <%= link_to "Delete User", user_path(@user), class: "btn btn-sm btn-danger",
                            method: :delete,
                            data: { confirm: "Are you sure?" } %>
          </button>
        </div>
      <% end %>

  </div>
</div>

<div class="container-fluid">
  <div class="row">
    <div class="col-3 card bg-light">
      <h2 class="card-title text-center"> Contact Info </h2>
    

        <div class="card-body">
        <p <a class="font-weight-bold"> Email Address: </a> <a class = "font-weight-normal"> <%= @user.email%> </a> </p>

        <p <a class="font-weight-bold" > Steam Profile: </a>  <%= link_to @user.steam_id, @user.steam_url, class: 'font-weight-normal' %> </p>

        <p class="font-weight-bold tp-2"> Steam Vanity: </p> <%=  @user.steam_vanity %> 

        </div> 

    </div>
  
    <div class="col-8 justify-content-center">
        <table class="table table-light ">
        <thead class="thead-dark"
        <tr>
        <th scope="col"> Game Name</th>
        <th>Developer </th>
        <th>Number of Players</th>
        <% if @looking_at_self %>
        <th> <button type="btn "> <%= link_to "Add Game to Library", user_add_game_path(@user), class: "btn btn-sm bt-dark" %> </button> </th>
        <% else %>
        <th></th>
        <% end %>
        </tr>
        </thead>
        <% @user.videogames.each do |game| %>
            <tr>
            <td><%= link_to "#{game.game_name}", videogame_path(game) %></td>
            <td><%= game.developer %></td>
            <td><%= game.number_of_players %></td>
            <% if @looking_at_self %>
                <td> <%= button_to "Remove from library", user_remove_game_path(@user), params: {game_id: game.id}, data: {confirm: "Are you sure?"} %></td>
            <% end %>
                </tr>
        <%end%>
    </table>
    </div>
    
  </div>
</div>