config/routes.rb
Rails.application.routes.draw do
  root "home#home"

  namespace :api do
    namespace :v1 do
      devise_for :users, :skip => [:sessions], controllers: {registrations: 'api/v1/users/registrations'} do
        devise_scope :user do
            get '/users/sign_out', to: 'devise/sessions#destroy'
        end
      end

      post '/users/sign-in', to: 'authentication#create'

      resources :videogames
      resources :users, except: [:new, :create] do 
        get 'add_game', to: 'users#add_new_game'
        post 'save_game', to: 'users#save_new_game_to_user' 
        post 'remove_game', to: 'users#remove_game_from_user_library'
        post 'create_and_save_game', to: 'users#create_and_save_game_to_user_library'
        post 'connect_steam_account', to: 'users#link_steam_account_to_user'
        post 'import_steam_library', to: 'users#import_steam_library'
      end
    end
  end
  get '*path', to: 'home#home', via: :all
end

app/models/videogame.rb
class Videogame < ApplicationRecord
    has_many :users_videogames
    has_many :users, through: :users_videogames

    validates :game_name, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/api/v1/videogames_controller.rb
module Api
  module V1
    class VideogamesController < ApplicationController
      before_action :set_videogame, only: %i[ show edit update destroy ]

      def index
        videogames = Videogame.all
        render json: VideogameSerializer.new(videogames)
      end

      def show
        videogame = Videogame.find(params[:id])
        render json: VideogameSerializer.new(videogame).serializable_hash.to_json
      end

      def new
        @videogame = Videogame.new
      end

      def edit
      end

      def create
        videogame = Videogame.new(videogame_params)
        
        if videogame.save
          render json: VideogameSerializer.new(videogame).serializable_hash.to_json
        else
          render json: { error: videogame.errors.messages }, status: 422
        end

      end

      def update
     

        videogame = Videogame.find(params[:id])
        
        if videogame.update(videogame_params)
          render json: VideogameSerializer.new(videogame).serializable_hash.to_json
        else
          render json: { error: videogame.errors.messages }, status: 422
        end
      end

      def destroy
        videogame = Videogame.find(params[:id])
        
        if videogame.destroy
          head :no_content
        else
          render json: { error: videogame.errors.messages }, status: 422
        end
      end

      private
      def set_videogame
        @videogame = Videogame.find(params[:id])
      end

      def videogame_params
        params.require(:videogame).permit(:game_name, :developer, :number_of_players)
      end
    end
  end
end

app/helpers/videogames_helper.rb
module VideogamesHelper
end

app/views/videogames/_form.html.erb
<%= form_with(model: videogame) do |form| %>
  <% if videogame.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(videogame.errors.count, "error") %> prohibited this videogame from being saved:</h2>

      <ul>
        <% videogame.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :game_name %>
    <%= form.text_field :game_name %>
  </div>

  <div class="field">
    <%= form.label :developer %>
    <%= form.text_field :developer %>
  </div>

  <div class="field">
    <%= form.label :number_of_players %>
    <%= form.number_field :number_of_players %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/videogames/edit.html.erb
<h1>Editing Videogame</h1>

<%= render 'form', videogame: @videogame %>

<%= link_to 'Show', @videogame %> |
<%= link_to 'Back', videogames_path %>

app/views/videogames/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Videogames</h1>

<table>
  <thead>
    <tr>
      <th>Game name</th>
      <th>Developer</th>
      <th>Number of players</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videogames.each do |videogame| %>
      <tr>
        <td><%= videogame.game_name %></td>
        <td><%= videogame.developer %></td>
        <td><%= videogame.number_of_players %></td>
        <td><%= link_to 'Show', videogame %></td>
        <td><%= link_to 'Edit', edit_videogame_path(videogame) %></td>
        <td><%= link_to 'Destroy', videogame, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Videogame', new_videogame_path %>

app/views/videogames/new.html.erb
<h1>New Videogame</h1>

<%= render 'form', videogame: @videogame %>

<%= link_to 'Back', videogames_path %>

app/views/videogames/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-9 col-md-7 col-lg-4 mx-auto">
        <div class="card card-signin my-5 border border-dark bg-light">
          <div class="card-body">
            <p class="card-text"> <strong>Game Name:</strong> <%= @videogame.game_name %> </p>
            <p class="card-text"> <strong>Developer:</strong> <%= @videogame.developer %> </p>
            <p class="card-text"> <strong>Number of players:</strong> <%= @videogame.number_of_players %></p>
            </div>
        </div>
    </div>
  </div>
</div>